
name: Python CI

on: [push, pull_request]


jobs:
  test:
    runs-on:  ubuntu-latest


    steps: 
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/checkout@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies 
      run: | 
        pip install -r requirements.txt

    - name: Run Test 
      run: |
        pytest 